spring.application.name=order-service
server.port=8081

spring.config.import=optional:file:../.env[.properties]
spring.datasource.url=jdbc:postgresql://localhost:5432/orderdb_phase2
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.kafka.bootstrap-servers=localhost:9092